apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-deployment
  labels:
    app: gin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gin-server
  template:
    metadata:
      labels:
        app: gin-server
    spec:
      containers:
      - name: gin-server
        image: rawanmostafa/ginserver:latest
        ports:
        - containerPort: 8083
