apiVersion: v1
kind: Service
metadata:
  name: http-service
spec:
  type: NodePort
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080
      nodePort: 30400